#!/bin/bash

a=1

while [ $a -lt 100 ]
do
   begin=`date +%s%N`
   ./a.out ./easy/"$a".cnf 1000
   end=`date +%s%N`
   runtime=$((end-begin))
   runtime=`expr $runtime / 1000000` 
   echo "runtime: $runtime ms"
   a=`expr $a + 1`
done
